import type { Metadata } from "next";
import { vazirmatn } from "./fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${vazirmatn.variable} h-full antialiased text-foreground bg-background`}
      dir="rtl"
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
